#STAGE 1: Build Stage

FROM node:20-slim as builder

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . .

#STAGE 2: Production Stage

FROM gcr.io/distroless/nodejs20-debian12

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app /app/

EXPOSE 3000

CMD [ "src/index.js" ]
