# Build Stage
FROM python:3.9-slim AS builder
WORKDIR /app

# install dependencies into /app/deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --target=/app/deps

# copy application code
COPY . .

# Final Distroless Stage
FROM gcr.io/distroless/python3-debian11
WORKDIR /app

# copy deps and app from builder
COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

# env vars
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/deps"

# app port
EXPOSE 80

# run app
CMD ["run.py"]
